spring:
  application:
    name: produto-ms
server:
  port: 6161

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    preferIpAddress: true

error:
  whitelabel:
    enabled: false